services:
  grafana:
    image: grafana/grafana:latest
    container_name: anomaly-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Basic Grafana configuration
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      
      # Security settings
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SECURITY_COOKIE_SECURE=false
      - GF_SECURITY_COOKIE_SAMESITE=lax
      
      # Plugin installation
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      
      # Database settings
      - GF_DATABASE_TYPE=sqlite3
      - GF_DATABASE_PATH=/var/lib/grafana/grafana.db
      
      # Paths
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      
      # Server settings
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      
      # Analytics
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      
    volumes:
      # Mount the anomaly detection database
      - ../anomaly_detection.db:/var/lib/grafana/data/anomaly_detection.db:ro
      
      # Persistent Grafana data
      - grafana-data:/var/lib/grafana
      - grafana-logs:/var/log/grafana
      
      # Configuration provisioning
      - ./provisioning:/etc/grafana/provisioning:ro
      - ./dashboards:/var/lib/grafana/dashboards:ro
      
    networks:
      - grafana-network
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  grafana-data:
    driver: local
  grafana-logs:
    driver: local

networks:
  grafana-network:
    driver: bridge